= 疾病诊断总结
:toc: auto

== 患者简介

患者：陈景峰
年龄：43 已婚
药物过敏：无
家族遗传疾病：无

=== 医院确诊

蛇口人民医院诊断：最早诊断支气管哮喘，目前维持湘雅诊断，嗜酸性粒细胞支气管炎 --- 门诊医生几乎都看过，住院主治医生，宛太，袁笼，康大海

湖南湘雅二院诊断：特发性嗜酸性粒细胞细支气管炎 --- 欧阳若云教授

深圳人民医院（呼吸研究所）诊断：疑似 EGPA? IgG4? --- 酆梦洁

无论哪种诊断结果，都不影响治疗方案：以激素治疗为主

目前2023-12月新增：高血压，高血脂，高血糖

=== 做过如下检查

1. 支气管激发，肺功能实验（舒张+弥散），N2O实验。
1. 支气管镜检查，肺泡灌洗液，肺部擦片，活检（嗜酸性粒细胞沁润）
1. 骨穿刺，寄生虫，肌电图
1. 痰培养（结核，真菌，曲霉），血液烟曲霉（广州金域）

=== 用药

1. 用过普米克令舒（气雾剂），舒利迭，目前用信必可 160 每日2吸
1. 口服泼尼松（每日四片）
1. 其他，阿斯美，切诺，安茶碱。根据需要随时调整，好的时候就不吃。

2024年开始服用：二甲双瓜（随三餐），瑞舒伐他丁（每晚1片），缬沙坦（早上一片）

=== 目前状况

经过几年激素治疗，目前嗜酸性粒细胞已经正常，几次感冒查血常规都是正常的，偶尔会出现升上，都属于正常状态。

在健康的状态下，每日服用激素，痰液很少，好的时候甚至没有条状痰，自我感觉嗜酸性粒细胞这块已无大碍。但是一旦感冒，前面的治疗就前功尽弃。

目前更严重的是，三高，平日常常头胀，尤其是吃完饭，颅压高，偶尔头晕，头痛。经过自己测血压和血糖，发现头部问题更多是高血压引起，偶不是血糖高。现在自己调整降压药，早和晚服用一粒缬沙坦，有缓解。

=== 发作表现以

感冒/感染引起发作

反复复发的过程总结：
1. 肺部/喉咙感染，不头痛，不发烧，不剧烈咳嗽，仅仅咳痰
2. 痰液粘稠（白色，胶水状或条状，颗粒装）伴有感染，黄痰，绿痰
3. 黄色浓痰-加重（条状，类似粉丝，米粉，短到1厘米，长到5厘米以上，很细）
4. 口服抗生素效果差
5. 痰咳不出来，雾化有效果
6. 血氧低

咯血问题：

咳血主要分为两类：一类是巨烈咳嗦引起，胸部不疼痛；另一类是支气管扩张，痰栓，咳嗦肺部剧烈疼痛，痰栓吸收/咳出后会痊愈。

一旦发病过程痰液出现血丝，或者粉色，支气管损伤，肺部会肿胀，呼吸困难，血氧饱和度88～92%，遇到这种情况，问了很多医生，也没啥好办法。此时雾化只能支持4个小时，信必可1小时，需要经常吸入，否则很快又会出现腹部肿胀，无法呼吸。

长期治疗，我发现这种情况，一定要加茶碱，先扩张支气管，解决呼吸困难问题，然后抗生素和激素解决感染，需要至少一到两周才能慢慢恢复。

=== 最佳治疗方案

经过长期住院，自己观察，尝试摸索，最佳治疗方案如下。

.肺部感染与治疗
---

社康开药，自我治疗：泼尼松+阿斯美（钾氧那明）+切诺+氨溴索片（出现咳血时不能使用，会加重）

门诊和住院的最佳治疗方案：甲强龙+氨茶碱/多索茶碱+任意抗生素（根据情况选择，左氧氟沙星/头孢曲松）+ 雾化（布地奈德+特布他林）

药物禁忌：不能使用异丙托修安，会出现气道干燥，口腔干燥，加重病情；当出现咳血时，不能使用氨溴索，乙酰半胱氨酸，等有刺激性的药，只会让肺部肿胀问题更严重。

2024年1元住院，新增观察：每次住院，心率140，血压140/100 以上，导致头胀，颅压高，眼睛快爆出来的感觉，注射多索茶碱后改善，头不痛了，血压也会降下去。
---

.三高问题
----
目前高血压比较严重，但我发现高血压，心率跟肺部感染关系很大，尤其出现肺部肿胀时，心率最高140多，血压也在140/100 之间。
一旦血液饱和度降低，心率就会很快，甚至达到120

平时测空腹血糖：6～8，饭后血糖：10左右
----

.药物的重要度排名
----
茶碱 > 抗生素 > 激素 > 其他

经过反复观察，由于目前嗜酸性粒细胞已经平稳，激素可以尝试减量，在健康的情况下，泼尼松减少2片，没有发现异样。
所有治疗方案，必须依赖茶碱，注射茶碱之后解决几个问题：扩张支气管，痰液容易排出，否则使用氨溴索效果都不好。
----

== 病史回忆2000年以前至2006年

一般一年会有两次感冒，集中在春秋。头痛，发烧，块装绿痰，很难咳出，胸腔火辣感觉。一般是感冒药+阿莫西林或胺边西林
治疗。

2005年左右持续咳嗽，看了半年，症状咳嗽，有颗粒痰，类似大米，透明有弹性，不溶于水。偶尔粉丝长条状。只是咳嗽，没有喘症状，没有哮鸣音。在市二医院，每次结果都是支气管炎，拍过X光，没有拍过CT。
每次都是头包薄亏脂，没有效果。后来开了莫西沙星，效果微乎其微。

无意中发现“氨茶碱”能改善我的症状，痰也能够顺利咳出。

== 2006年在深圳市二医院确诊哮喘

继续咳嗦不断，每次看呼吸内科拍X光，按照支气管炎治疗，一年多，不断吃抗生素，效果不好。最后医生建议做支气管激发试验。

做完支气管激发试验和N2O后确诊哮喘，采用布地奈德气雾剂（普米克），用药后很快就起效效果明显。

吸入普米克气雾剂治疗（现已停产，外形根万托林一样，咖啡色），每天三吸，吸入第二天就有效果，颗粒形状痰液咳出后，就不再咳嗽。医生也开了万托林，基本用不上。

=== 2007年-2009年

一年后医生建议减量，每天2吸。最后慢慢停用，2009一年多没有复发。

=== 2010至2017年

后来也是因为感冒复发，记得是在罗湖国贸附近的医院（门诊），呼吸困难，感冒哮喘一起治疗。当时做了血常规，白细胞，中性粒细胞，嗜酸性粒细胞比较高。

* 口服：感冒药
* 静滴：倍露米松（记不太清了）+左氧氟沙星
* 雾化：布地奈德+沙丁胺醇+氨溴索
* 开药：普米克气雾剂（国产仿药）每天2吸入（用了两支效果很差），切诺（每天三粒，每次一粒），阿斯美（每天3次每次2粒，一些感冒药

后面在市二医院，换成“舒利迭”，每天两吸。用了两年

这个期间症状主要是轻微咳嗦，没喘息症状。万托林基本没有用过。 2002-2010一直在玩户外运动，登山，穿越，露营，游泳。等消耗体力，体能和耐力的运动，不影响工作生活。

病情还是向前发展的，相比之前条状痰增多（不是很多，偶尔有一条，透明的），也比之前难咳出。

后面感觉舒利迭也不太好用，尝试换信必可160，感觉效果比舒利迭好（感觉舒利迭药粉颗粒没有信必可细小，不容易吸进小气管），信必可增加了福莫特罗成分更容易排痰。

期间在北大医院看过耳鼻喉，鼻子干燥流血，黄绿色鼻涕。做过鼻内窥镜，第一次发现有息肉，医生建议保守治疗，吸入布地奈德比喷雾剂（每天2吸）。治疗效果非常好，后面鼻炎理疗预防都是吸入该药。

== 2018年港大医院门诊总结

2018年之前病逝回忆不十分准确，当时没有做详细记录，仅凭记忆，仅供参考。

2018年主要在港大医院门诊和梅林关民乐村社康

感冒容易感染，一般是鼻子，然后喉咙，再到肺部，不发烧，不头痛，

过程：首先是鼻塞，然后喉咙，肺部，呼吸困难，憋气，肺活量减少（风流速仪器自测）。

主要在社康治疗：普米克令舒+沙丁胺淳，切诺，氨溴索口服液，孟鲁司特钠等等，雾化后能支持4-6小时。

久治不好，前往港大医院：右侧肺叶下部咳嗦出现剧痛，有出血。去港大医院呼吸科，做了CT，有支气管扩张。开了氨溴索片，信必可换成320...... 好像还有消炎药。医生建议同时看耳鼻喉，做CT 发现有息肉，开药辅舒良，鼻炎主要是干燥流血。

回家后吃药氨溴索片，痰液也难咳出，押紧肺部患处可减轻疼痛，这时感觉有痰液从患处挤压出来，黄痰。用了一周多痰栓咳出，约3MM粗两厘米长，疼痛消失，里面痰液顺利排出。

一旦形成痰栓，吸入信必可效果就不好，无法把药粉吸入到细支气管。于是自己买了雾化器，在社康开药自己雾化，普米克+特布他林，一次6只，3天。

[TIP]
====
洗澡发现右下边两肋骨间又肿块，肿块包裹肋骨，平时不同，主动用力按压才会痛，CT也未发现异常。复诊问过医生也没有准确定义，再观察。后面几个月后慢慢肿块消逝。
====

=== 2018 总结

2018年出现新的症状就是一旦肺部感染，大量痰栓堵塞气管，出现走路时血氧跟不上，大口喘气，必须停下休息。

后面发生活右侧上肺叶，中肺叶，左右，上下等处同样的痰栓，也是剧烈疼痛，出血，排出后痊愈。痰都是条状，树根状（支气管链接细支气管）。已经习以为常，为了防止痰栓出现，常被氨溴索，切诺。但是严重感染痰栓数天就可以形成痰栓。

....
        呼吸内科治疗总结：
        1. 布地奈德+沙丁胺醇雾化，有时增加胺嗅索。
        2. 抗生素头孢
        3. 切诺
        4. 信必可吸入 160
        5. 胺茶碱片
        6. 阿斯美
        7. 孟鲁司特钠
        8. 氨溴索口服液/甲羊斯坦口服液
        9. 其他中成药，枇杷露
        10. 感冒药

        医生建议看耳鼻喉科，做过鼻内窥镜，鼻炎平静期，有息肉：建议使用布地奈德鼻喷雾剂

        病情一直反反复复

        2018年9月（左右）出现咳嗽疼痛剧烈，偶尔出现血丝，在香港大学深圳做CT，确认支气管扩张。肺部右叶

        治疗方案：
        1. 按嗅索片
        2. 切诺
        3. 头孢
        4. 信必可改为 320
        5. 孟鲁司特钠
        6. 福舒良鼻喷雾剂
        7. 同时在社康继续做布地奈德+沙丁胺醇雾化

        治疗一段时间，时好时坏，肺部陆续轮流出现左上，左下，右上，中部等等位置堵塞的情况。咳嗽疼痛，用力挤压咳，可以咳出一段，一节，粉丝状痰。 
            
....

2018年一直坚持游泳，病情好的时候，可以一次游5公里

[TIP]
====
其他发现:发现有时流泪，泪水刺痛眼睑，类似切洋葱时的感觉。记忆力不如之前,视力最近两年有下降.
====

== 2019年蛇口人民医院门诊和住院总结

2019年搬家的深圳南山区，开始在蛇口人民医院做规范化门诊治疗。

=== 2019年蛇口医院门诊总结

看过唐文辉、黄强华、盛艳、陈院长，全科和急诊等医生

陆续采用排除法检测查病原：CT检查，流感抗原，肺结合，肺支原体，真菌培养，15项过敏原筛查，粪便，IgE…. 详见检验资料。

以上均阴性

....
治疗方案，不同医生用药习惯不同，主要：
        1. 抗生素，头孢，左氧氟沙星，莫西沙星
        2. 切诺/阿斯美（有些医生用，有些医生不用该药）
        3. 信必可 320 （并当着医生面吸入，已确认正确使用）
        4. 门诊雾化：布地奈德+特布他林雾化
        5. 其他中成药：克黄止咳胶囊，苏黄止咳胶囊
        6. 激素：泼尼松片 （不同医生不同用法，有是早上2片，下午2片。有些医生，早上6/8片，每日一次）
        7. 孟鲁司特钠
....

在治疗中我不断总结，主要的问题是不断产生谈，堵在支气管，产生谈的速度大于排出。当很多气管被堵塞后，吸入信必可已经无法到达患处。这是雾化效果更好，于是购买雾化器，在家自行雾化，每日2次（布地奈德+特布他林）。

关于谈栓，谈栓出现在左/右两侧肺部的上中下，也就是上面好了，下面复发，六个位置六轮来。有时吸入空气时能感到谈栓向内侧运动，呼气时又被推向内侧，咳嗦剧痛，用力按压患处可减轻疼痛，同时咳出黄痰，知道可见谈栓被咳出才能康复，谈栓1～3毫米组，长度1～3厘米，一旦咳出病情立刻减轻。

[TIP]
====
发现 泼尼松片 最有效果，但医生只能开18片，也不建议长期服用。
所以仍没有彻底治疗好，经常复发。
====

=== 2019年4月份蛇口住院

第一次住院，2019年4月份开始出现走路（100米左右）就必须休息，雾化效果也不如之前。医生建议住院：

检查项目：CT检查，流感抗原，肺结合，肺支原体，真菌培养，15项过敏原筛查，粪便，寄生虫，IgE,
IgM, 心肌酶…. 详见检验资料。

医生：宛医生

....
        前三天保守治疗：
        1. 低流量吸氧（当时血氧 91%），
        2. 左氧氟沙星，
        3. 布地奈德+特布他林+异品拖嗅安雾化
        4. 多索茶碱         
            
....

治疗不理想，血氧下降
88%，医生建议使用激素，甲泼尼龙琥珀酸钠，左氧氟沙星改为头孢.加入激素后效果明显，每次雾化时不断吐出大量痰液，铁锈色为主，条状。血氧量每天都会上涨，独院第五日（使用激素第二天）后血氧量 95-97%，身体已经行动自如。

住院 10日，出院后带药：医生建议口服一段时间泼尼松，信必可320（每日两次），孟鲁司特钠，头孢

出院几周后，有反复情况，期间看过门诊，医生开了莫西沙星，吃了两周无效。

=== 2019年6月蛇口住院

第二次住院，2019年6月，再次发作，直接选择住院，跟上次住院同一个医生，用药与之前相同。住院5天出院。

检查出白色念珠菌，注意入院前没有检查出，是出院期间检查出来，医生建议出院后再检查两次，后面去复查，没有检查出来。

出院后咳嗽全无，身体状态良好。

决定锻炼身体，每天骑行20-50公里的自行车。但是半个月后痰液稍稍粘稠，少量咳嗽，有颗粒状痰，多喝水好些。

由于之前几个医生都怀疑可能是家里新房装修过敏，我跟家人决定去旅游，去青海。期间携带着药品，但是病情仍缓慢加重。
开始有黄痰，在当地买了头孢氨苄，效果不理想

回来后又去了另外的住所（惠州）开始出现黄痰，去当地社康，注射了阿奇霉素，按嗅索，地塞米松（打了两次，药物有效），后回到深圳家里，不久后再次住院。

=== 2019年9月中秋前住院

住院前看了陈院长门诊，他发现我激素敏感（有效）怀疑是ABPA，建议我住院并检查支气管镜。

第三次住院，2019年9月中秋前，这次医生是袁笼医生，增加检查项目：

....
        治疗方案主要：
        1. 左氧氟沙星
        2. 切诺
        3. 布地奈德+特布他林雾化+异丙托嗅安
        4. 孟鲁司特钠
        5. 富马酸酮替芬片
        6. 奥美拉唑肠溶片
        7. 苟橼酸胶囊
            
....

连续用药 10日，咳嗽不断加剧，每晚无法入睡，期间医生不建议使用激素。

支气管镜检查（擦片+活检）发现白色菌丝，采用氟康唑治疗（用药5日，第一天2瓶，早上一瓶，晚上一瓶，后面4天，每天一瓶），维持支气管扩张采用
噻托嗅安粉吸入治疗。 期间检查 IgE 已经达到 从600 升到 800 多。

咳嗽加剧，会诊后，医生决定晚上服用了可待因+泼尼松。医生建议到上级医院治疗，决定去深圳人民医院。

[TIP]
====
注意：住院期间一次吃苹果，腮腺肿胀，刺痛，询问医生，建议观察，两日自然消退。
之前在惠州也出现过唾液腺肿胀，4天左右，中间注射过地塞米松好转。

从这次开始便关注起腮腺肿胀问题
====

=== 转院到人民年总结

从蛇口人民医院转到深圳人民医院继续治疗，主要是 “蛇口人民医院”检查之外的一些没有检查的项目，或无法检查的项目，重点是曲霉。

所有检查均阴性，包括白色念珠菌。详见“出院小结”

最终治疗方案仍然是 依靠： 甲泼尼龙琥珀酸钠（静脉注射）+左氧氟沙星，连续用药5天，痊愈出院。

注意：
后来在人民医院住院期间，一次吃干虾仁，再次出现腮腺，唾液腺肿胀，刺痛，也请耳鼻喉，口腔会诊。没有查出原因。我反应的口腔干燥问题，口腔医生怀疑是异丙托秀安（抗胆碱药物）引起的。

出院后一直带口罩，包括睡觉。自己住一个房间，24消逝开空调和空气净化器。

=== 2019-10-10 腮腺肿胀

2019-10-10号左右，这次与之前病情不同，最开始耳朵与乘坐飞机产生的耳压感觉一样，听力下降，有耳鸣，耳后腮腺肿胀较硬，内耳道刺痛，痒。开始喉咙有黄痰，有时绿痰，偶尔痰中有非常少的血点，后面几天咳出大量血丝。外耳正常，不发烧，不头痛。
担心进一步恶化，服用出院时开的，克拉霉素，效果不明显。

....
        去蛇口人民医院，耳鼻喉门诊，检查 听力，腮腺B超，鼻咽镜。医生治疗方案
        1. 头孢
        2. 泼尼松片
        3. 中成药，比拜克胶囊
            
....

腮腺已经好转，听力正常，咽喉仍有痰（浑浊白痰，稍绿色），稍有有喘息（感觉喘息来自咽喉，而不是肺部），夜里咳嗽，睡觉咽喉处有哨鸣音。白天能运动（骑车10公里）咽喉干燥，咳嗽，需要不停喝水。每天检测血氧量正常
93-96%，没有大面积肺部感染

== 长沙湘雅二医院

携带了所有CT片和资料前往湘雅，去湘雅还有一个原因是，深圳医生怀疑居住环境的问题，妹妹住在湖南，房子是老房子，换个环境观察一下。

=== 2019-10-29 住院

医生：欧阳若云，参与过奥马朱单抗临床三期研究，还曾在深圳蛇口医院坐诊过。

湘雅首次提出病因是嗜酸性粒细胞沁润，做了全院大会诊，出院小结确诊是：特发性嗜酸性粒细胞细支气管炎。治疗方案是：每日泼尼松4片，伊曲康唑服用三个月（检出有念珠菌）

在湘雅医院所做项目：各种痰液培养，各种血液检查，支气管镜，肺功能，烟曲霉，血液寄生虫，肌电图，等等

在深圳如此频繁，间隔密度很短住院，有可能跟服用“孟鲁司特钠”有关，该药会加重嗜酸性粒细胞沁润肺间质，湘雅医生不建议在用孟鲁司特钠。

以下简单记录，前期为了检查没有使用激素，身体状态差，没有记录太多。

10月31号下午做雾化，布地奈德+沙丁胺醇+异丙托嗅胺。雾化后出现声音嘶哑，腮腺肿胀，听力微下降。继续观察

11月1 号做支气管镜，查出真菌感染，停掉激素药物（普米克令舒），下午 15 呼吸困难，找管床医生加雾化，沙丁胺醇+异丙托嗅胺。雾化后少量咳痰呼吸有改善。23:30左右在次呼吸困难，咳嗦加剧，找值班医生做雾化+两片阿斯美。晚上睡眠还好

次日2号7点左右，醒来血氧92掉到 85%出汗，喘息，血氧一直回不到90%。找护士吸氧，吸氧一直维持在93，明显感觉肺活量下降，无法吸入更多的空气。9:00钟达到 95%仍然全身不舒服，不如平时不吸氧92%的状态，一动血氧就掉会88%。9:10
雾化后身体不适有缓解，也吐出一些谈。但仍离不开氧气，病情有加重。

总结：可能根停掉激素药物有关，需要考虑替代激素治疗方案。

晚上硬扛，躺着，侧卧喉咙都会发出哮鸣音，导致咳嗦。只能趴着，勉强睡了两小时，一旦咳嗦，全身颤抖，无法呼吸，全身出汗，呼吸频率混乱，心跳加速，有大小便失禁感觉，近乎抓狂，濒死挣扎。

3号，值班医生请求上级，中午增加 布地奈德雾化有改善。支持到18:30分，再次需要雾化，又加了布地奈德。雾化过程中咳嗦剧烈，出汗，挣扎。无法控制小便、只能使用塑料袋临时解决。有吐出脓痰，雾化后慢慢进入平稳期，症状有缓解。晚上4:10呼吸困难，要求做雾化加激素，雾化过车起效慢，雾化过程中咳嗦剧烈，全身出汗，心慌，剧烈挣扎，极速呼吸，小便失禁少量尿出。血氧上不去89%，心率140左右，接近濒死感觉。雾化起效后头痛，呼吸仍然节奏混乱。尝试深呼吸回复呼吸节奏，用了很久。5:25左右回复稳定。

11月四号，白天增加 甲强龙，效果非常好，中午可以下床，下午去做肌电图，不用吸氧，可以自由行走。晚上未吸氧，右侧躺血氧89%，左侧躺90%，平躺 90% 容易咳痰，趴着90%。坐姿94%。

总结：有些睡眠体位会压迫肺部，出现不同的血氧数据，睡眠后身体血氧消耗低，会达到95-98%。

11月5号，甲强龙使用后 血氧 94% （不吸氧）

....
我跟医生建议：
1. 使用雾化器+注射用蒸馏水+氧气驱动。水雾吸入增加肺部湿度。
2. 去掉异丙托嗅胺，腮腺微刺痛，口干，鼻腔干燥，呼吸道干燥。只用布地奈德+沙丁胺醇
            
....

11月6号，早晚两次甲强龙，血氧恢复到 98%，不吸氧 95%。痰液，咳嗦减少，身体康复到 70% 发现98%高血氧，剧烈咳嗽是头会发晕，类似久蹲后站起来的感觉，另外吸氧后有些亢奋，睡不着。还发现血管充盈，量血压是，手臂、手掌非常胀

6号，我起床不吸氧，血氧量98%，咳痰上部泡沫浮起，底部微黄浓痰沉淀。感觉肺部气道敏感，闻到保洁阿姨拖地的消毒水咳嗦起来。咳出痰液后，又慢慢好些

[TIP]
====
“孟鲁司特钠” 会加重嗜酸性粒细胞沁润

本品上市使用后有以下不良反应报告：超敏反应(包括过敏反应、管性水肿、皮疹、瘙痒、荨麻疹和罕见的肝脏嗜酸性粒细胞浸润)、夜梦异常和幻觉、嗜睡、兴奋．激惹、包括攻击性行为．烦躁不安、失眠、感觉异常/触觉障碍及较罕见的癫痫发作，恶心、呕吐、消化不良、腹泻．ALT和AST升高．罕见的胆汁淤积性肝炎：关节痛，包括肌肉痉挛的肌痛；出血倾向增加．挫伤；心悸；和水肿。

哮喘和过敏性鼻炎的病理生理过程相关。在哮喘中．白三烯介导的效应包括一系列的气道反应，如支气管收缩、粘液分泌、血管通透性增加及嗜酸性粒细胞聚集。在过敏性鼻炎中．过敏原暴露后的速发相和迟发相反应中．鼻粘膜均会释放与过敏性鼻炎症状相关的CysLTs。鼻I为CysLTs激发会增加鼻部气道阻力和鼻阻塞的症状。

接受包括白三烯受体拮抗剂在内的抗哮喘药物治疗的患者，在减少全身皮质类固醇剂量对．极少病例发生以下一项或多项情况：嗜酸性粒细胞增多症、血管性皮疹、肺部症状恶化、心脏并发症和/或神经病变(有时诊断为Churg-Strauss综合征——一种系统性嗜酸细胞性血管炎)。虽然尚未确定这些情况与白三烯受体拮抗剂的因果关系．但在接受本品治疗的患者减少全身皮质类固醇剂量时．建议应加以注意并作适当的临床监护。
====

=== 湘雅出院后总结

PEF（峰流速仪监控） 600 左右，血氧量 99-97%，每日服用泼尼松（4片）+信必可（早晚两吸），伊曲康唑（早晚各一片）。伊曲康唑服用2个月后停药。

饮食方面可以吃任何东西，包括辛辣食物，生吃大蒜，葱等等，没有不良反应。每天步行5公里，偶尔跑步。没有什么痰，也几乎不咳嗦。

——

期间肺部感染（12月中旬左右），没有感冒症状，黄痰咳嗦，自行服用头孢氨苄，普米克+特布他林雾化，切诺，泼尼松4片。

服用一周后好转。偶尔咳嗽，尤其是长时间说活。凌晨4点需要起来咳嗦一阵，把痰液咳出再入睡。有时增加2片泼尼松能维持不会产生痰栓堵在支气管。PEF（峰流速仪监控） 400-550 之间，血氧量 95%

——

最近一次感染，1月份，没有感冒症状，春节前一周，家人没有感冒，痰液呈黄色，少许绿色，呼吸困难 PEF 下降，痰液粘稠，偶尔有血丝，不易咳嗽。

蛇口人民医院查了 IgE 550。嗜酸性粒细胞 15%， 做了CT ，PEF 400左右，血氧94-96%，开药克拉霉素1盒。服用后克拉霉素有效（早晚各一粒）。

=== 由于疫情没有复诊成功

湘雅出院一年，年底回湖南顺便找欧阳医生复诊。

打算回湖南乡下过年，然后再到湘雅复诊，结果武汉疫情原因，湘雅医院呼吸科停诊，所有医生支援武汉，已经挂号却没复诊成功。

得知湘雅停诊加上疫情，停工停学，不急于回深圳，就安心留在乡下，也比较安全，但是肺部始终感染没有解决。

克拉霉素用完，使用阿奇霉素替代，服用两天，效果不好。去了村里卫生所，只有罗红霉素，服用两天，效果不好。去乡里医院、头孢曲松+左氧氟沙星
双联治疗，注射两次，效果不好。

疫情期间不好就医，最后去镇上药店买了5瓶泼尼松，克拉霉素胶囊（把药店买断货，一次买了15盒，早晚各一粒）有效果。服用后黄痰减少，容易咳出。持续住用到2月22日（约一个月），黄痰全部消失。期间激素没有停，每天4片。

乡下烤火取暖，鼻子干燥，流血，黄鼻涕。克拉霉素对鼻炎也有效果。

1月23日从湖南桃源回到深圳后每天病情都有好转，PEF 恢复到 600，血氧 98%

总结：治疗感染目前发现克拉霉素效果较好，口服需要较长的疗程。之前还有一些氨茶碱缓释片，就跟克拉霉素一起服用。

=== 困扰问题

哮喘病发状态，感染时的病发状态是细支气管栓塞，最直接反映是 PEF 下降，最低只能吹出 PEF 300，同时血氧量伴随下降91-94%。走路，上楼梯，呼吸频率增加，咳嗦加剧。运动过快大脑缺氧。有时连哮鸣音也没有。

右侧背部在湘雅出院时就有栓塞已经4个月时间，弯腰，蹲下时感觉酸麻胀，尤其是厕所解大便憋气时更明显，但是几次CT上看不到，感觉应该是肺部靠外侧。最近一次检查，IgE 550左右，嗜酸性粒细胞 15%。

== 2020年

=== 人民医院呼吸研究所住院检查

从湖南回到深圳，身体已经恢复（非病发住院），住院主要是做一次彻底检查。此时人民医院已经升级为呼吸研究所，副主任：酆孟杰，王凌伟主任，陈所长，都做了会诊，同时也在广州呼吸研究所做了病理会诊。

本次检查很全面：除了湘雅检查项目之外，增加了血液科骨穿刺检查（骨髓和骨质），心脏彩超，腮腺彩超，全身加强CT（舌头，肝脏，肾脏，腹部，等等）心脏MRT，支气管镜（含活检，灌洗液），广州金域送检曲霉和肺泡灌洗液，华大基因肺泡灌洗液。

将湘雅的病理片寄到深圳与人民医院的病理片一同寄到广东呼吸研究会诊，此次会诊是怀疑EGPA，我为此准备了深圳人民医院10片白片，之前在湖南湘雅又切了15片白片。会诊结果：病变符合支气管的病理改变。本片未见真菌。

发现 IgG4指标升高，主任动用私人关系联系了北京协和医院，多次沟通，最后因病理标本不足不能精确诊断，IgG4疾病较难诊断，需要做腹腔镜，去出大面积标本。考虑后放弃，再观察。

住院检查期间，采用湘雅的方案，4片泼尼松，每天3次雾化，切诺，茶碱缓释片，护胃药

检查未发现异常，最终出院小结：疑似EGPA？IgG4? 由于EGPA也好IgG4也好都是激素治疗手段，治疗仍然是：每日4片泼尼松，出院带药还有茶碱缓释片，信必可160，切诺等等常规药

=== 2020年上半年病情总结

经过长期观察和总结得出下面数据

==== 周期性发作

目前的病情是：好一段时间（一到三周），然后慢慢加重，再慢慢康复，反反复复。

病情好的时候，哮喘症状全无，痰液很少，基本不咳嗦，可以连续爬 30层楼。

加重的时候，大量痰液，里面有条状痰液，咳嗦喘息，PEF下降到300，爬3层楼就大口喘气。一到三周后又慢慢好转。

==== 哮喘症状观察

经过长期观察，和其他哮喘病人交流。我发现我的哮喘跟他们不太一样，他们很多是无痰。

哮喘由痰栓引起，痰液粘在气管壁上，气管敏感，产生激烈反映。一旦咳出痰液/痰颗粒/痰栓后哮喘症状很快改善。

每次信必可吸入后很快就可以咳出痰液，哮喘症状很快改善。

如果治疗方案能控制或减少痰液分泌，应该对治疗有很大帮助。

喘息方式的不同：我的喘息是需要用力收缩膈肌，尽量排空肺部，然后深呼吸。

==== 腮腺的观察

发现腮腺的肿胀是伴随病情的发展，最好的时候左侧腮腺的腺体如花生大小，持续了三周。病情加重的时候能肿胀到3倍大小。同时口腔伴有烧灼感（上火的感觉）。

病情好的时候，腮腺分泌出液体，病情差的时候，腺体分泌出跟痰液一样的胶水状（粘稠）液体。右侧腺体分泌较少。

==== 舌苔的观察

病情好的时候是粉色，病情加重的时候一层白色，可以刮下来。一旦发现舌苔退去基本上是要康复了。

==== PEF与血氧饱和度观察

支气管堵塞后PEF和血氧都会下降，吸入/呼出空气总体体积减少了。

最近痰多，晚上不能及时排出，晚上血氧92-94%，早上起来头痛，可能跟血氧低有关。白天正常95%
以上。

==== 用药观察

服用泼尼松后改善痰栓，期间改变剂量观察结果。

每日2片，会形成痰栓，但是可以排出（咳出），脸上痘痘慢慢减少。

每日3片，痰液软化，胶水状，容易咳出。

每日4片痰液会减少一点，但是脸上痘痘非常多。

但是病情严重时，虽然每日服用
4片泼尼松，但是感觉没有效果。仍然痰栓呈现粉丝状，项链状，有一定硬度，有一定弹性不易拉断，类似小孩吃的橡皮糖，没有煮熟的马铃薯粉条，不溶于水。

泼尼松+阿斯美，咳嗦减少，痰液容易排出。服用后容易瞌睡，由于每天要开车，吃完一瓶后没有在继续吃。

泼尼松+茶碱缓释片，也有效果改善。

使用信必可后，几分钟内会咳出痰液，改善哮喘

==== 最终总结

只要没有痰，哮喘症状消失，咳嗦消失，任何饮食都不影响（辛辣食物）。腮腺伴随病情发展，病情好的时候腮腺正常。最近发现眼袋消失。

眼袋和腮腺指向 IgG4，后续常规检查要监控 IgG4 变化。

上半年基本没有出现过咳血现象。右侧肺叶中部背后，有些体位仍会出现涨，刺感觉，病情加重时更明显，但是多次CT都未发现异常。暂时忽略。

=== 2020年下半年哮喘病情总结

2020年下半年我尝试激素减量并观察发现，泼尼松2片的无法控制痰栓，仍然会形成粘稠条形痰液。3片的时候痰液软化，最终恢复成4片。

中间感冒过两次，感冒加重谈栓形成，出现微黄，微绿的痰液。服用抗生素，切诺，阿斯美等等常规治疗，也会去社康开雾化药物（特布他林+普米克令舒）

下半年重点观察腮腺肿胀的问题，出现过多次肿胀，平时微肿，上眼睑出现过肿胀。有过几次痊愈，痊愈后腮腺很小，柔软。

==== 为什么激素不能随便减量？

经过长期观察感受，这是我对激素作用的理解。

激素疗法跟抗生素不同，例如肺部感染，通过抗生素治疗，抗生素对抗感染，可以不断抑制细菌，随着身体的康复细菌会慢慢减少，此时可以减少服用抗生素的剂量，直到康复为止，便可停用。

激素效法更像糖尿病人注射胰岛素，今天注射的剂量，只负责今天，明天还要继续注射，不能随意停药。

我们服用激素是为了压制免疫系统，降低嗜酸性粒细胞和IgG4浆细胞，也就是不让免疫系统制造嗜酸性粒细胞，激素并不能杀死这些细胞。今天服用的只管今天，并且剂量不足就达不到效果。如果今天没有服用激素，嗜酸性粒细胞就会增多，次日服用激素，只能控制控制今天免疫系统不再产生嗜酸性粒细胞，昨天的细胞仍然存在，此处出现哮喘症状，服用激素是不会太多改善的。必须等袋老的细胞死亡代谢掉，同时服用激素，不再产生新细胞，才能发挥激素的作用。

==== 尝试乙酰半胱氨酸雾化

从19年住院开始，标准治疗没使用过乙酰半胱氨酸雾化，在蛇口医院医生说乙酰半胱氨酸是哮喘禁用药。我想可能是他的独特气味，会加重气道反应，尤其是过敏型哮喘的。我的情况不同，我对气味从不过敏，并且20项过敏筛查都是阴性，所以很想试试，于是让社康给我开了乙酰半胱氨酸雾化。

我对“氨臭索”的效果不太满意，只能把希望寄托在了“乙酰半胱氨酸”上。之前也服用过“乙酰半胱氨酸冲剂”气味难喝，没有感觉特别有效，但是没有试过雾化。在有医院的时候经常看到
COPD 患者使用该药。

乙酰半胱氨酸（Acetylcysteine）为黏液溶解剂，具有较强的黏痰溶解作用。其分子中所含的巯基能使痰液中糖蛋白多肽链中的二硫键断裂，从而降低痰液的黏滞性，并使痰液化而易咳出。本品还能使脓性痰液中的DNA纤维断裂，因此不仅能溶解白色黏痰，也能溶解脓性痰。对于一般祛痰药无效的患者，使用本品仍可有效。

普米克令舒+硫酸特布他林+乙酰半胱氨酸，每天2次，早晚一次。雾化吸入后效果还不错，症状缓解了。过了几天胸部咳嗦剧烈疼痛，需要用力按压疼痛的地方再咳嗦，才能缓解疼痛，这种情况之前也常常发生，偶尔还会出血，见怪不怪了，起初拍CT是支气管扩张，后来CT也诊断不出来支气管扩张了，没有定论。断断续续做了
12 支，感觉之前堵塞了很久的谈栓开始咳出。在咳嗦肺部就不疼痛了。

这次尝试证明，至少我跟其他哮喘患者病情不太一样，可以使用该药。后面如果出现谈栓，可以继续使用这种治疗方案，长期观察一下再说。下次去医院，跟医生沟通一下。

=== 哮喘用化痰，排痰药物对比

以下是我尝试服用化痰/排痰药物自身感受的总结

* 促进肺部纤毛运动
* 润滑呼吸道
* 溶解痰液
* 扩展支气管

哮喘患者长期服用的化痰排痰药物有下面几种。

使用最广泛的是氨溴索类药物，他的主要功能是润滑呼吸道。

有片剂，口服液，针剂和雾化吸入。

点评：一般感冒引起的痰多，氨溴索效果比较好，我主要用来预防感冒进一步发展引起谈栓堵塞支气管。细支气管效果并不好，每次服用片

本品为粘液调节剂，主要作用于支气管腺体的分泌，使低粘度的唾液粘蛋白分泌增加，高粘度的岩藻粘蛋白产生减少，因而使痰液的粘稠性降低而易于咳出。口服起效快，服用4小时可见明显疗效。

点评：与氨溴索效果差不多，相当于百事可乐和可口可乐的区别。

乙酰半胱氨酸（Acetylcysteine）为黏液溶解剂，具有较强的黏痰溶解作用。其分子中所含的巯基能使痰液中糖蛋白多肽链中的二硫键断裂，从而降低痰液的黏滞性，并使痰液化而易咳出。本品还能使脓性痰液中的DNA纤维断裂，因此不仅能溶解白色黏痰，也能溶解脓性痰。对于一般祛痰药无效的患者，使用本品仍可有效。

点评：乙酰半胱氨酸是使用的时候要谨慎，很多医院明确哮喘禁用该药，我是痰液咳不出来，发现这款药，请求医生试一试。虽然他标明可以溶解痰液，但是真的不是想象的那样，吃下去立马把痰溶解，也需要一个疗程。哮喘患者使用该药容易出现剧烈咳嗽，我到没有引起哮喘发作。只是觉得刺激气管，哪个药的味道比氨溴索还难闻。

氨茶碱为茶碱与乙二胺复盐，其药理作用主要来自茶碱，乙二胺使其水溶性增强。不溶于甲醇、乙醇、乙醚。本品对呼吸道平滑肌有直接松弛作用。其作用机理比较复杂，过去认为通过抑制磷酸二酯酶，使细胞内cAMP含量提高所致。

氨茶碱氨茶碱药物对支气管平滑肌的松弛作用是最强的，可使支气管扩张，肺活量增加，作用较为持久，尤其是对痉挛状态的支气管效果显著，另外氨茶碱还有扩张冠状动脉，增加心肌供血，加强心脏收缩力的作用。多用于马牛的肺气肿，以及犬因心力衰竭而引起的肺充血（心性喘息）的平喘

点评：茶碱类药物很多，便宜的5元100片一瓶的氨茶碱，还有包装精美的茶碱缓释片，也有复方甲氧那明（阿斯美）。
5元一瓶的药店容易购买，应该常被，茶碱缓释片大药房和医院才有。

综合来说阿斯美效果最好，它包含三种成分(甲氧那明，氨茶碱和扑尔敏)，里面的扑尔敏成分容易打瞌睡，不适合驾驶。还有一点需主要，低血氧时服用阿斯美比较危险，扑尔敏造成嗜睡，此时血氧低于80%以下，患者不知道，也醒不来，第二天醒来头会痛。

另外茶碱类药物与其他药物同时，有些药，会增加其他药物在肺部的浓度。隐约记得在那种药的说明书上看到过。

切诺（桉柠蒎肠溶软胶囊），适应症为本品为粘液溶解性祛痰药。适用于急、慢性鼻窦炎。适用于急慢性支气管炎、肺炎、支气管扩张、肺脓肿、慢性阻塞性肺部疾患、肺部真菌感染、肺结核和矽肺等呼吸道疾病。亦可用于支气管造影术后，促进造影剂的排出。改善气管粘膜纤毛运动，促进呼吸道腺体的分泌作用，并使粘液移动速度增加，有助痰液排出。

点评：桉柠蒎肠溶软胶囊是不错的排痰药。服用时一定注意，必须饭前，不能用热水，热水会溶解胶囊。一旦胶囊破裂，在胃部释放药物，就会产生胃酸，非常难受。呼吸会有橙子皮的味道。饭后吃药也会出现这种问题。

服用切诺出现过不消化的情况，没有在肠道中吸收，排除是有点像拉肚子，便中带有明显的橙子柠檬味道，肛门附近如同涂了薄荷。

有时连续服用切诺没有代谢，大脑发胀，一咳嗦，眼前一片黑，大脑翁的一声，多少情况人还有意识，不会摔倒。我晕倒一次，半清醒状态下，安全倒地，趴在地上，过了一会清醒过来。

咳嗦出现血丝后使用氨溴索或乙酰半胱氨酸，会加剧咳嗦，两款药的味道较刺激气道。

== 2021年总结

=== 2021年上半年总结

上半年疫情，很少出门，出门必带口罩。由于疫情戴口罩全国呼吸门诊就诊都有所下降。

所以上半年控制的非常好，没有感冒，没有感染，坚持服用泼尼松，有时忘记吸信必可，都不会有任何症状。

=== 2021年下半年总结

下半年7月份开始到公司上班，乘坐地铁较多。

国庆节
6号左右在地板上睡觉，出现鼻塞，7号流清鼻涕。然后从鼻子向鼻腔上颚发展，最后是咽喉，直到肺部。与之前的感冒类似，出现黄痰。

这次主要问题是：感冒感染，黄痰，痰液粘稠，痰液在肺部边缘底部，极难咳出，服用氨溴索也没有改善，呼吸产生哮鸣音，痰液在气道壁震颤，刺激引起痉挛咳嗽，剧烈咳嗽，后出现痰中带血丝血点，淡淡粉红色痰，每次咳出后呼吸有改善。

去社康看后，用了头孢夫辛，氨溴索片，布地奈德+特布他林雾化。自备药（切诺，泼尼松
早晚各2片）。 可能是社康用药剂量不够，头孢早晚个一粒，所以感染没有控制。
服用氨溴索一样痰多不好咳出，痰多和哮鸣音引起剧烈咳嗽，每次咳出痰后，呼吸顺畅很多。剧烈咳嗽还会带出少量血丝。

去蛇口医院门诊，换成克拉霉素，每次两粒，黄痰转为白色，痰仍然很多，白色有气泡。蛇口医院特布他林缺药，替代的沙丁胺醇也没有，只开了布地奈德，乙酰半胱氨酸。所以单用布地奈德雾化效果不好，平时用万托林替代，效果也不好。

昨晚睡前状态还好，服用了克拉霉素1粒，泼尼松2片，阿斯美1粒。痰液比较多，凌晨2点起来咳出一部分，平躺呼吸困难，右侧卧呼吸有哮鸣音不舒服，后来左侧卧也有哮鸣音，最后坐在地地毯上，趴着沙发睡，早上7点起来，痰液咳不出，血氧低，只用布地奈德做了雾化，效果不好。血氧上不来，剧烈咳嗽后动弹不得，出汗，颤抖。

然后打电话120急救，血氧85%，吸氧到92%，送到蛇口医院，继续吸氧，氧气流量7-8，急诊医生建议注射氨茶碱+地塞米松，我要求把地米换成甲泼尼龙琥珀酸钠。输液后气道感觉湿润，咳出一些痰，仍有淡黄色痰，肺活量至少增加一倍，血氧稳定在97%左右，11:00左右分离院。准备去深圳市人民医院呼吸研究所住院。

离院后步行回家，可以步行走了两站地，喘气可以接受。

---

总结，这次感染与之前几次过程一样，从鼻子开始，蔓延到肺部。
不过这次痰液粘稠液态，（之前2020年都是有弹性的条状，树根装）。液态痰液是因为一只服用泼尼松。

另外由于剧烈咳嗽，容易咳出血丝，一旦出现血丝，肺部就会出现肿胀，肺活量下降，很难呼吸。

出现血丝后使用氨溴索或乙酰半胱氨酸，会加剧咳嗦，两款药的味道较刺激气道。所以用了两次就停了，没出现血丝可以使用，有一定效果。

阿斯美中的扑尔敏成分会造成嗜睡，晚上吃有风险，尤其是血氧低的时候，此时熟睡感受不到。有时阿斯美中的氨茶碱成分剂量以不足以控制我目前扩张支气管所需剂量。

由于长期对血氧低产生了耐受度，所以感受不到病情严重程度，尤其是静坐的时候低血氧更是感受不到。常常耽误治疗。

此次急诊发现 氨茶碱
效果较好，好于之前用的哆嗦茶碱。起效快，但是心率会非常高。

---

下午在人民医院急诊留观，等待第二天住院。

急诊留观，做了雾化，沙丁胺醇+布地奈德+盐水。
加盐水湿化肺部效果好些，咳出一些黄痰和绿痰，也有少量的条状痰。

风流速仪 400，吸氧后血氧 99%

早上，风流速仪 300 不到，吸氧血氧 97%

此次住院常规治疗，甲强龙+消炎+口服茶碱缓释片+切诺。金域送检烟曲霉

住院5天，出院带药，常规药，信必可160，茶碱缓释片，莫西沙星，切诺，护胃药。

我要求试试“美卓乐”，因为泼尼松需要肝脏代谢，起效慢。

---

这次是最重的一次叫了120，事后经过回忆发现竟然是吃错药造成了。泼尼松吃完之后，随手便拿了一瓶，没有仔细看，那是一瓶谷维素（之前失眠吃的）瓶子大小、形状、药片大小（略大一些）、药片形状一样，只有商标不同，极难分辨，就这样大概吃了有20天，其间早上偶尔吃办公室放的一瓶，混合吃就没有发现激素剂量不够。

== 2022年总结

....

发作病情主要表现是：

1. 嗜酸性粒细胞升高，IgE 升高。 使用激素治疗很快好转，容易复发复发。
2. 痰液胶水状，粉丝状，颗粒状（QQ糖，橡皮糖，有弹性，不溶水）不容易咳出
3. 肺部发炎，黄痰/绿痰，痰液堵塞气管，剧烈咳嗽，导致血氧量不达标
4. 胸部膈肌抽筋
5. 不头痛，不发热
6. 睡觉趴着可以缓解咳嗽
7. 凌晨2点至5点，部分痰液集中在咽喉，有喘鸣声，醒来剧烈咳嗽，清空痰液，才能继续入睡
8. 目前 IgE 400左右，偶尔咳嗽可以接受，600 说话时比较咳嗽，最严重IgE 800 剧烈咳嗽
9. 目前信必可160 控制不了病情，只能维持 2～6 小时左右
10. 说话的时候更容易咳嗦，有时不讲话可以很久不咳嗦。

关于喘息：
喘息方式，需要用力收缩膈肌，尽量排空肺部，然后深呼吸。
最严重的时候，肺部肿胀，风流速仪300不到，痰液栓塞，氧气无法吸入，这种情况常见与咳出血丝的情况。如果没有血丝，不会反复随机出现肺部肿胀。不出血丝茶碱，信必可都能控制，一旦出现血丝，茶碱和信必可维持时间达不到6小时。

血氧量：
平时血氧95%左右，如果运动，散步，骑车是血氧会升到 99%。经常骑车 20-50公里，17年的时候还能游泳3-5公里。

环境因素：
1. 起初怀疑是装修问题，2017年老房子粉刷过墙面，2018年搬家，新房子
2. 但是 2019年去青海旅游（海拔3000多）半个月后去惠州住了几周，19年去湘雅治疗住湖南妹妹家（08年装修的）
应该可以排除环境因素，平时对气味敏感，烟味，尾气等，但气味不哮喘发作

其他发现：
感觉记忆力下降，平时看书，看完一本后，基本记不住内容

饮食方面：
* 出院后可以吃任何食物，包括辛辣食物
* 病发时吃辛辣食，病情加重，痰多

暂时未查出原因：
IgG4 升高，待观察
腮腺常常肿胀
        
....

=== 2022年元旦

2022-01-03
日左右痰多，吃克拉霉素，头孢效果不佳，蛇口医院急诊，甲强龙+氨茶碱+左氧氟沙星+吸氧。下午7:00
左右离开

=== 2022年春节

从2021之后CT结果，肺部毛玻璃影像消失。明显能感觉肺活量比之前大了，即使严重的时候，总的来说是向好的方向发展，虽然有时控制不佳。

一月份控制不佳

2022-01-03 日左右，痰多，吃克拉霉素，头孢效果不佳，蛇口医院急诊，甲强龙+氨茶碱+左氧氟沙星+吸氧。下午7:00 左右离开

2022-01-25 日左右，痰多，咳嗽白痰，吃切诺+阿斯美+之前家里剩下的头孢，克拉霉素 + 每晚吸氧3～4小时。效果一般，维持

2022-02-1～3号 在惠州过年，期间服用 切诺+阿斯美/氨茶碱（开车服用氨茶碱，在家服用阿斯美）+ 莫西沙星，痰液逐渐增做，晚上至少起来咳嗦三次，每次大量绿脓痰，目前偏黄色。偶尔里面有一点点血丝。


长期观察发现一旦有血丝，肺部就容易出现肿胀，呼吸困难，发生时间随机，外界稍刺激就可能出现，例如翻身，使用信必可/沙丁胺醇能缓解，只能维持一段时间。这段时间每天使用信必可2次不够。一旦气道恢复，就不会出现急性肺部肿胀这种问题。

最近几次加重与以往不同的是有肺活量，但吸不进去氧气

2022年2月4日蛇口住院

就诊诉求与疑问：

1. 新冠疫苗是否可能打
1. 奥马朱单抗是否可以打
1. 快速气到快速重建
1. 激素治疗是否需要调整
1. 腮腺问题
1. 是否要经常监控 IgE，来控制激素摄入量
1. 胸部肋骨问题，按压疼痛
1. 右侧下部常常，痰多时会胀，咳出后消失，有时会联系多天，经常出现，CT未发现异常
1. 长期使用激素，鼻腔常常分泌白色不透明分泌物。常常咳出的谈也是这样，是否服用激素后，本身气管就会分泌过多分泌物，也是导致谈栓，容易感染（为细菌提供较好的生存环境）。

发现切诺的副作用：服用切诺有时头胀，咳嗽后，会昏迷（如同蹲久后起身）

晚上值班医生查房，听了肺部问是不是感觉全是谈，问了病史，疑是 “细支气管炎” 医生诊断与我的感受吻合，以往都是按支气管哮喘方向诊断和治疗，始终没有新突破。

补充，咳嗽的时候按压/挤压胸部更容易咳出，喘息/呼吸方式，收缩膈肌排空肺部，然后吸气

—

2022-12-30

今天从医院回来，人满为患，急诊科都是抬进去的老人。

我有嗜酸性粒细胞闭塞性支气管炎，平时最怕感染，最近新冠开放，我还是很担心的。结果全公司大面积羊，我没有感觉，网上说过敏体质不易羊，我的 IgE 平时就很高，我的症状就是持续咳嗦，大量白痰，不过再之前就已经咳了快三周，那是每天还检测核酸都是正常的。

白天再公司咳的厉害，晚上回家不带口罩反而不怎么咳。偶尔觉得鼻腔和喉咙分泌物多，回家睡一觉，第二天有正常了。也就是说白天再公司受到病毒攻击，晚上回到家睡一觉第二天就恢复。三天前扁桃体发炎肿大，自测一次，是阳性。过两天消肿，没有再测。

后来由于咳的厉害，喉咙和肺部咳出血丝，这个我并不担心，之前经常遇到过，怕的是感染，所以吃了抗生素。果不其然又感染了，黄痰变多。今天咳嗦肺部疼痛，呼吸困难，血氧浓度 90%，赶紧去医院，呼吸科没有号，看急诊，拍了CT，医生说轻度感染，氨茶碱+头孢曲松，医生不给打甲强龙。我之前的质量方案都是 甲强龙+氨茶碱+头孢曲松。

现在急诊缺医生，各种科室医生去值班，上次遇到的是心内科，也是不给我用激素。

以前去急诊，血氧94%都让我吸氧，现在90%都跟我说没事，憋的好难少，看看急诊室，也确实没有地方吸，只能回家用吸氧机自己吸。


== 2023年

2023年重点是「嗜酸性粒细胞」哮喘管理

从确诊我的病是由嗜酸性粒细胞引起的，必须使用激素治疗，如今已经服用激素4年，这四年病情只能说时好时坏。

=== 激素的副作用·白色分泌物

除此之外，鼻腔中每天会分泌大量白色分泌物。我甚至在想，很多时候肺部的栓塞就是来自激素产生的分泌物，无法及时排出所致。

总的来说，激素治疗对病情控制还不错，但是曲线始终起起伏伏，不稳定。

最近几次感冒，去医院查血常规，发现嗜酸性粒细胞已经在正常范围。计划激素慢慢减量。

=== 激素副作用·血糖

服用泼尼松的另一个副作用就是影响血糖，呼吸道内血糖过高，更容易感染，也会减慢康复时间。

=== 鼻腔出血/痰液中带血

这是给我最大的困扰，一旦出现这种情况，很快就会出现细菌感染，黄痰/绿痰，难咳出，扩散快，很快就会恶化。需要长期服用抗生素维持，直到出血情况好转，这个过程至少几个月。

此前我问过很多医生，出现呼吸道谈中血丝的问题，是咳嗦引起，问到是否有什么方法可以快速修复，都没有解决方案。尝试使用维生素对策：维生素 B2 + 维生素 A + 维生素 D + 维生素 E

=== 眼睑和腮腺肿

这几年腮腺肿胀/刺痛减少，但是长年会肥大。被另一个困扰上眼睑浮肿，不清楚原因，也不知道去什么科检查。

=== 耳鸣问题

我怀疑是腮腺体积大，压迫耳部神经所致，或者是长期服用药物所致。


== 其他回忆

=== 腮腺与唾液腺问题

平时吃辛辣食物是腮腺会痒，按摩后缓解。体检问过医生，吃辛辣食物出现这种情况正常。

有时（偶尔）从腮腺分泌出白色透明条状分泌物，长约2-4厘米，一毫米粗。没有在意。

第一次，唾液腺肿胀
2016年（记不太清）吃橙子，下颌双侧唾液腺肿起来，酸胀，按摩后，约30分钟慢慢恢复消肿。

外观方面并不明显，抬起舌头，口腔中明显看到肿胀。

第二次，在蛇口人民医院住院，2019年4月左右，吃苹果，腮腺突然肿胀刺痛，外观不太明显，医生摸过后，说做B超可能看不出来，建议观察，3天后消肿恢复。

平时我喜欢挤压腮腺，排出液体，这样腮腺会变得柔软。

第三次，2019年5月份，在惠州家中，不记得怎么发做的，双侧腮腺，双侧下颌唾液腺均出现肿胀，刺痛。外观能看到腮腺肿，下颌看不出。持续了一周多，慢慢恢复。

第四次，从蛇口转到人民医院，住院期间吃虾仁，出现双侧腮腺肿胀刺痛，顺便去了口腔科，检查无异常，无堵塞，无结石，腮腺分泌少，医生怀疑是异丙托修安，沙丁胺淳类药物引起的。

第五次，2020年4月1日—2020年4月4日，无特别饮食，出现腮腺肿胀，微刺痛。

总结，从湘雅医院回来后，有一段时间没有出现腮腺和唾液腺问题。2020～2021
多次出现。

右侧腮腺分泌比左侧少，右侧肿起来也比左侧大一些。

平时挤压按摩，排出液体，恢复的快一些

肿胀的时候，腮腺分泌较粘稠，胶水果冻状。颜色都是透明白色，我常常挤出来放在手指上查看。

其他发现，有时流泪，泪水辣眼睛，如同切洋葱。这种情况最近已经消失。

与其他病人在群里交流发现一个查出 IGG4 的人也有腮腺肿胀问题，另一个是泪腺
